language: java
node_js:
- 10
sudo: enabled
services:
- postgresql
addons:
  apt:
    packages:
    - libgconf-2-4
install:
- npm install -g wait-on
- npm ci
before_install:
- psql -c 'create database webprojectdb;' -U postgres
deploy:
  provider: heroku
  api_key:
    secure: wjmhjxpktnQ+ZHIV118hDA3DQR0nb1/yT2760OMpFvw/msNNrPwTGBtCY+8Sl9K+x1lnvs9C3ZGrojqqwznFR+SayLx9WDOfqrg4iuTSue7Lm/HZHb3FzFOOfeZhyo4MpIZ5F34DN1CzPyXMXjzWgrxExItu3tYWI37p9kxr+Z3OTuAJoFPRKT0gyz62Ne6EpS4bo/HBb8XeZktSF5vgnizkXVl3ReIQ8tL0TKLc8O2TyjFstjPwIeJzJQxU2DGU+tvKumtCPIJTFriXcl3z+amCT9ILcPnq6pWaiWxmJvXX0a9ueu9i3Y1DGenLks10aD926dYb8bN/hL0ibqJpR3zcoyH6PcxwKODkOn0f5bjsRIhR9zb9tqaM5Is+ZBIH+AhS2VgPbHATxPynJVgxXZD9F2FxymmAjGsnZvXCyQiBeA05/tsqCsVA8RGRC9zTFqZ1hadxzzZsXq+rNUrASR+tFvOboyWS5CBcdcM9uzhwMPEP+4TaYQVIha/4Ea7G4pAvUfb/PXR4Ybmi/TZ2H8cEUqI8p61fkztJjeTx3n9mNmwoqj8w4zUKsIefRvhkYUvEr4gzAADSDVRsc2ggML3InHRwO8TP0/9Cxp2DAjr1RCLCv8pWBFLMS7jb+Vt6yLFEvwpDJpSGib0MGs6Cspo28j2e8J3+NtjsqzH+84w=
  app: thebayofpirates
  on:
    repo: Rankhole/TheBayOfPirates
cache:
  npm: true
  directories:
  - "~/.cache"
