language: java
node_js:
- 10
sudo: enabled
services:
- postgresql
addons:
  apt:
    packages:
    - libgconf-2-4
install:
- npm install -g wait-on
- npm ci
before_install:
- psql -c 'create database webprojectdb;' -U postgres
deploy:
  provider: heroku
  api_key:
    secure: pQPxFCFXrfhGXdbzh7+LfC5XoFJi2HgEAgdML8LIEeR/yDgT14VGDbn6r2r4qn58ukJbyEZRCRMJOaRuJjeZTw1DLKauDPyr6k/CXlkvOhER2FfW3JYT3gcejwLfQ53+Ml3qMrFRPiHQ6uKpqhhdCHq2SvG2P+UHpQTzv2Yng/MrmW2jZoWpc6wbqrPvZQKxBRE9vWQX2VbCndusvV5EVDAJEp2/jzxUL+m139wteTwHEWMthx78RhkvwnzUHOmNT/MS2+9x0Jzgwe/EmKkqyCf/ysU2MSqAj3YIOtssGCFBIcxxmCLlDG6KEGoYL84mXamzri1ja+lmsoIsBUgwuYyuJale5Lzg3mFN/zHS2px9rnyttzIeBPxA9bnO6F3srPti/9v/Dng7mwplYlR4srBf33PQJhta5DgdCji7MVuIaikrz+ZyAzKXWqJ2DijEPDQG0eP20jd0zjrFnMSpCkCck9GwURJjl90GTtBoRFIohwuXJ0/gEYIZrWqob7QvZSAaT6Y37jolPz6O2+EQ5d2h6MmCWhUxsFnBKxs8dSfJfXbuvgsGwKzILZW9cruHILJVnSK43OqzBablPnbvzpbawLCwVJrtGViPahVnRcSxBkNU2yadL1vUuox3/JxvLuyDmo+WIYfJ68Us5aubHgAjFG2gUAOvV6nz5uW4QHw=
  app: thebayofpirates
  on:
    repo: Rankhole/TheBayOfPirates
cache:
  npm: true
  directories:
  - "~/.cache"
