language: java

sudo: enabled

services:
        - postgresql

addons:
        apt:
                packages:
                        - libgconf-2-4

install:
        - npm ci

before_install:
        - psql -c 'create database webprojectdb;' -U postgres

deploy:
        provider: heroku
        api_key:
                secure: "c2f25de9-9de9-43df-9180-f6db4a7aa18b"
        app: thebayofpirates

script:
        - $(npm bin)/cypress run


cache:
        npm: true
        directories:
                - ~/.cache
